name = "my-router"
type = "webpack"
account_id = "085eb14f95a179f56e42dad3d215212d"
route = "stage-university.redislabs.com/*"
zone_id = "b37f240fd18cdd2e2c2f11ad3ed21dd5"

[vars]
TAHOE_HOST = "stage-university.redislabs.com"
STATIC_HOST = "redislabs-training.github.io/redis-university-static-site-prod"
