type = "webpack"
account_id = "085eb14f95a179f56e42dad3d215212d"
zone_id = "b37f240fd18cdd2e2c2f11ad3ed21dd5"

[env.stage]
name = "redisu-stage-router"

# These are the URL paths that the static site should be
# served for in stage.
routes = [
    "stage-university.redislabs.com/",
    "stage-university.redislabs.com/site.webmanifest",
    "stage-university.redislabs.com/sitemap.xml",
    "stage-university.redislabs.com/robots.txt",
    "stage-university.redislabs.com/register*",
    "stage-university.redislabs.com/certification/*",
    "stage-university.redislabs.com/certification-enrollment/*",
    "stage-university.redislabs.com/certifications/*",
    "stage-university.redislabs.com/assets/css/*",
    "stage-university.redislabs.com/assets/favicon/*",
    "stage-university.redislabs.com/assets/images/*",
    "stage-university.redislabs.com/assets/js/*",
    "stage-university.redislabs.com/courses",
    "stage-university.redislabs.com/courses/ru101*",
    "stage-university.redislabs.com/courses/ru102j*",
    "stage-university.redislabs.com/courses/ru102js*",
    "stage-university.redislabs.com/courses/ru102py*",
    "stage-university.redislabs.com/courses/ru330*",
    "stage-university.redislabs.com/courses/ru201*",
    "stage-university.redislabs.com/courses/ru202*",
    "stage-university.redislabs.com/courses/ru203*",
    "stage-university.redislabs.com/courses/ru301*",
]

vars = { TAHOE_HOST = "stage-university.redislabs.com", STATIC_HOST = "redislabs-training.github.io/redis-university-static-site-stage" }

[env.production]
name = "redisu-router"

# These are the URL paths that the static site should be
# served for in production.
routes = [
    "university.redislabs.com/",
    "university.redislabs.com/site.webmanifest",
    "university.redislabs.com/sitemap.xml",
    "university.redislabs.com/robots.txt",
    "university.redislabs.com/register*",
    "university.redislabs.com/certification/*",
    "university.redislabs.com/certification-enrollment/*",
    "university.redislabs.com/certifications/*",
    "university.redislabs.com/assets/css/*",
    "university.redislabs.com/assets/favicon/*",
    "university.redislabs.com/assets/images/*",
    "university.redislabs.com/assets/js/*",
    "university.redislabs.com/courses",
    "university.redislabs.com/courses/ru101*",
    "university.redislabs.com/courses/ru102j*",
    "university.redislabs.com/courses/ru102js*",
    "university.redislabs.com/courses/ru102py*",
    "university.redislabs.com/courses/ru330*",
    "university.redislabs.com/courses/ru201*",
    "university.redislabs.com/courses/ru202*",
    "university.redislabs.com/courses/ru203*",
    "university.redislabs.com/courses/ru301*",
]

vars = { TAHOE_HOST = "university.redislabs.com", STATIC_HOST = "redislabs-training.github.io/redis-university-static-site-prod" }

