type = "webpack"
account_id = "085eb14f95a179f56e42dad3d215212d"
zone_id = "b37f240fd18cdd2e2c2f11ad3ed21dd5"

[env.stage]
name = "redisu-stage-router"

# These are the URL paths that the static site should be
# served for in stage.
routes = [
    "stage-university.redislabs.com/",
    "stage-university.redislabs.com/site.webmanifest",
    "stage-university.redislabs.com/sitemap.xml",
    "stage-university.redislabs.com/robots.txt",
    "stage-university.redislabs.com/courses/*",
    "stage-university.redislabs.com/certification/*",
    "stage-university.redislabs.com/certifications/*",
    "stage-university.redislabs.com/assets/*",
    "stage-university.redislabs.com/courses"
]

vars = { TAHOE_HOST = "stage-university.redislabs.com", STATIC_HOST = "redislabs-training.github.io/redis-university-static-site-stage" }

[env.production]
name = "redisu-router"

# These are the URL paths that the static site should be
# served for in stage.
routes = [
    "university.redislabs.com/",
    "university.redislabs.com/site.webmanifest",
    "university.redislabs.com/sitemap.xml",
    "university.redislabs.com/robots.txt",
    "university.redislabs.com/courses/*",
    "university.redislabs.com/certification/*",
    "university.redislabs.com/certifications/*",
    "university.redislabs.com/assets/*",
    "university.redislabs.com/courses"
]

vars = { TAHOE_HOST = "university.redislabs.com", STATIC_HOST = "redislabs-training.github.io/redis-university-static-site-prod" }

